# Site
title:              Jonti Talukdar
bio:                'Jonti is a fun loving engineer who seeks pleasure in exploring new places and meeting new people. He also loves referring to himself in the third person. A final year student of Electronics and Communication Engineering at Nirma University (India), he is currently pursuing active research in the field of Computational Intelligence Paradigms and Soft Computing techniques in Embedded System Design. Having been exposed to both hardware and software design techniques, his research interests lie in the multi-disciplinary fields of Intelligent Systems Design, Computer Vision, Neural Networks, Computer Architecture and VLSI Design. He is passonate about using AI/ML techniques to facilitate Processor design optimization, Circuit Testing and Manufacturing. You can reach him through any of the following networks.'
description:        "Hi, welcome to my portfolio. My research interests - Intelligent Systems Design, Computer Architecture, Computer Vision, Deep Neural Networks and VLSI Design."
reading_time:       true
words_per_minute:   125
logo:               'assets/img/ocean.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://jontitalukdar.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   jontitalukdar

# Social
# if you don't have any of social below, comment the line.
google:
  plus:            109063222364059782087
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:               jonti.talukdar.05@gmail.com
#twitter:            username
facebook:           profile.php?id=100006255737607
github:             jontitalukdar
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          jontitalukdar
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           UCc0I5IL5qtSY2WdduUxrZUQ
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
