# Site
title:              Jonti Talukdar
bio:                Jonti is a 2nd year Master's candidate at the Department of Electrical and Computer Engineering at Duke University (Durham, NC) specializing in Hardware Engineering with a focus on VLSI Testing, Design and Verification. He is currently pursuing active research in the field of VLSI Testing, Functional Fault Modeling as well as working on developing analytical models for SET (transient) propagation in combinational logic.
description:        "Hi, welcome to my portfolio. As a student majoring in Computer Engineering engineering, my research interests lie at the intersection of VLSI (Back End) and Systems design (Front End), including the multi-disciplinary fileds in both hardware and software domains like VLSI Design, DfT, Hardware Verification, RTL Integration, Deep Neural Networks and scripting automation."
reading_time:       true
words_per_minute:   125
logo:               'assets/jonti_duke_final.jpg'
background:         'assets/img/cherry_blossom.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://jontitalukdar.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   jontitalukdar

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            109063222364059782087
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:               jonti.talukdar@duke.edu
#twitter:            usernamee
facebook:           profile.php?id=100006255737607
github:             jontitalukdar
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          jontitalukdar
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           UCc0I5IL5qtSY2WdduUxrZUQ
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
